language: c

dist: trusty
sudo: required

git:
  depth: 1
  lfs_skip_smudge: true

before_install:
        #        - sudo apt-get update -qq
        - sudo apt-get install bc
        - if [ `uname -m` = x86_64 ]; then sudo apt-get install libc6-i386 lib32stdc++6 lib32z1; fi

        #        - sudo apt-get install -y gcc-arm-linux-gnueabihf
        #        - arm-linux-gnueabihf-gcc --version


before_script:
          #   - export MYHOME=$PWD
#        - wget http://releases.linaro.org/14.08/components/toolchain/binaries/gcc-linaro-aarch64-linux-gnu-4.9-2014.08_linux.tar.xz
#        - tar xf gcc-linaro-aarch64-linux-gnu-4.9-2014.08_linux.tar.xz
#        - export PATH=$PATH:$PWD/gcc-linaro-aarch64-linux-gnu-4.9-2014.08_linux/bin

script:
          #        - export ARCH=arm
          #        - export CROSS_COMPILE=arm-linux-gnueabihf-
        - cd $TRAVIS_BUILD_DIR

#        - make allnoconfig
#        - make -j`getconf _NPROCESSORS_ONLN` all

#       - make alldefconfig
#        - make -j`getconf _NPROCESSORS_ONLN` all

        - make allyesconfig
        - make -j`getconf _NPROCESSORS_ONLN` all

